Chore/pivotal 183795701 biostudies e2e setup GitHub repository and first gherkin test implementation
EBIBioStudies/biostudies-e2e pull request #1
Opened 2022-11-14 20:36 UTC by msrada94

Pivotal ID # 183795701: Biostudies-e2e setup github repository and first gherkin test implementation

https://www.pivotaltracker.com/story/show/183795701

2022-11-14 21:06 UTC, Juan-EBI requested changes
Looking good please check comments

2022-11-14 21:06 UTC, Juan-EBI commented on src/test/kotlin/test/steps/SubmitSteps.kt
> +        headers.clean().addTokenSession().addSubmissionType().apply { contentType = TEXT_PLAIN }
why performing request (generic) is cleaning and seting some headers. header should be set only in the steps we said we are setting them. and clean should happen only after performing operation

2022-11-14 21:06 UTC, Juan-EBI commented on src/test/kotlin/test/steps/SubmitSteps.kt
> +        headers.clean().addTokenSession().addFormDataContentType()
why we are adding the session token in this step?

2022-11-15 09:11 UTC, msrada94 commented on src/test/kotlin/test/common/LoginSerialization.kt
> +class LoginDeserialization : StdDeserializer<LoginUser>(LoginUser::class.java) {
Actually, it is not needed. So, deleted.

2022-11-15 09:12 UTC, msrada94 commented on src/test/kotlin/test/common/LoginUser.kt
> +data class LoginUser(val login: String, val password: String)
thanks

2022-11-15 09:47 UTC, msrada94 commented on src/test/kotlin/test/common/LoginSerialization.kt
> +
my fault

2022-11-15 09:55 UTC, msrada94 commented on src/test/kotlin/test/steps/SubmitSteps.kt
> +        headers.clean().addTokenSession().addSubmissionType().apply { contentType = TEXT_PLAIN }
yes, functions should do only one thing

2022-11-15 11:35 UTC, msrada94 commented on src/test/kotlin/test/steps/SubmitSteps.kt
> +        headers.clean().addTokenSession().addFormDataContentType()
bad practice, it is amended

2022-11-15 11:42 UTC, msrada94 commented on src/test/resources/features/submit.feature
> +    And http response the JSONPath value "$.sessid" is saved into "token"
true, was replaced by "is extracted from http response the JSONPath value {string} and saved into {string}"

2022-11-15 22:46 UTC, msrada94 commented on src/test/resources/features/submit.feature
> +      | files | $example.txt |
it was modified now it uses the variable name that stores that file

2022-11-18 01:31 UTC, Juan-EBI requested changes
Looking good please check comments

2022-11-18 01:31 UTC, Juan-EBI commented on .gitignore
> +.DS_Store
missing line break (apply everywhere else)

2022-11-18 01:31 UTC, Juan-EBI commented on build.gradle.kts
> +    testImplementation("org.springframework:spring-web:5.3.23")// enables restTemplate
lets removeall this  comments they are not necesary at alls

2022-11-18 01:31 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        formDataBodyRequest.add(files, FileSystemResource(file))
this looks incorrect, we are hardcoding is a file but step does not said anything about it. So it looks lime magic assumsitions rather than step implementation.

2022-11-18 01:31 UTC, Juan-EBI commented on src/test/kotlin/test/common/Util.kt
> +
lets move this methods into the SubmitFeatureContext

2022-11-18 01:31 UTC, Juan-EBI commented on src/test/kotlin/test/common/SubmitFeatureContext.kt
> +    lateinit var responseBody : String
the reponse body should be HttpSteps and not here

2022-11-19 19:03 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        formDataBodyRequest.add(files, FileSystemResource(file))
totally agree, my fault. Solved!

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/common/SubmitFeatureContext.kt
> +object SubmitFeatureContext {
we need a simple context class that allows to , set variable and get variable

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/common/SubmitFeatureContext.kt
> +    fun createFormData(map: Map<String, String>): Map<String, Any> {
this function is not related at all with generic variables

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +    fun getHttpStatusCodeAndBodyResponse(statusCode: String, body: String) {
*assert

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        fun stringToHttpMethod(method: String): HttpMethod {
do not codifique types in method, Kotlin is already strongly typed language

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +    fun performJsonRequest() {
this is the same as performRequest, looks like this one is not needed them

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +    fun getHttpCode2(statusCode: String,jsonPath: String, name: String) {
this function is incorrect you are doing two things here

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        variables[TOKEN_SESSION_ID] = value
this is magic, this is wrong

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/resources/features/submit.feature
> +Feature: make a submission
Submit a submission with a text file

2022-11-21 22:30 UTC, Juan-EBI commented on src/test/resources/features/submit.feature
> +  Background: Here is the setup for the scenarios
either we put content that has value and meaning or we leave it empty.

2022-11-22 11:56 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +    fun getHttpStatusCodeAndBodyResponse(statusCode: String, body: String) {
yes, other bad named functions were amended

2022-11-22 14:20 UTC, msrada94 commented on src/test/kotlin/test/common/SubmitFeatureContext.kt
> +    fun createFormData(map: Map<String, String>): Map<String, Any> {
It's true, I made this function solve a specific problem and named it according to the other context, it's not general

2022-11-22 14:20 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        fun stringToHttpMethod(method: String): HttpMethod {
thanks

2022-11-22 14:20 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +    fun performJsonRequest() {
deleted!

2022-11-22 14:21 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +    fun getHttpCode2(statusCode: String,jsonPath: String, name: String) {
solved, the steps were splitted

2022-11-22 14:22 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        variables[TOKEN_SESSION_ID] = value
solved!

2022-11-22 14:23 UTC, msrada94 commented on src/test/resources/features/submit.feature
> +  Background: Here is the setup for the scenarios
I agree

2022-11-22 21:51 UTC, Juan-EBI submitted a review, later dismissed
LGTM pleaee check minor comments

2022-11-22 21:51 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +            .mapValues { ContextVariables[it.value.replace("$", "")] }
this one need to use getValueString instead of replacing manually

2022-11-22 21:51 UTC, Juan-EBI commented on src/test/kotlin/test/common/ContextVariables.kt
> +    operator fun get(key: String): Any {
this is not used actually this should be getValuedString

2022-11-22 21:51 UTC, Juan-EBI commented on src/test/kotlin/test/common/ContextVariables.kt
> +    fun setAll(map: Map<String, Any>) {
this is not setting all but putAll

2022-11-22 21:51 UTC, Juan-EBI commented on src/test/resources/features/submit.feature
> +    And take from response the JSONPath value "$.sessid" and saved into "token"
maybe 

`And the JSONPath value "$.sessid" from response is saved into "token"`

2022-11-22 22:33 UTC, msrada94 commented on src/test/resources/features/submit.feature
> +    And take from response the JSONPath value "$.sessid" and saved into "token"
it's better, more concise and easier to read

2022-11-22 22:41 UTC, msrada94 commented on src/test/kotlin/test/common/ContextVariables.kt
> +    operator fun get(key: String): Any {
actually should be `get`  because returns `Any` type. In the case of the `getValuedString`, I renamed it as `getString` because returns String type

2022-11-22 22:41 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +            .mapValues { ContextVariables[it.value.replace("$", "")] }
comment on the next review comment

2022-11-28 11:50 UTC, Juan-EBI approved these changes
great changes

2022-11-28 12:04 UTC, merged