Pivotal ID # 184353778: Add gitlab pipeline to run e2e
EBIBioStudies/biostudies-e2e pull request #14
Opened 2023-01-30 21:50 UTC by msrada94

https://www.pivotaltracker.com/story/show/184353778

List of the changes:
* Added jobs to build and run e2e tests

2023-01-31 13:36 UTC, Juan-EBI requested changes
please check comment and remove code not part of this PR

2023-01-31 13:36 UTC, Juan-EBI commented on .gitlab-ci.yml
> +  script: gradle clean test
if you clean basically you are losing everything result of build, so gradle will need to build again

2023-02-20 11:23 UTC, Juan-EBI requested changes
Looking good please check comments

2023-02-20 11:23 UTC, Juan-EBI commented on .gitlab-ci.yml
> +    - gradle clean build -PbiostudiesDir=$BIOSTUDIES_DIR -PdockerUser=$CI_REGISTRY_USER -PdockerPassword=$CI_REGISTRY_PASSWORD --stacktrace
why do we need docker user and password if authentication is realdy save in `config.json`

2023-02-20 11:23 UTC, Juan-EBI commented on .gitlab-ci.yml
> +    - BIOSTUDIES_DIR="$(mkdir ~/biostudiesMount && pwd)/biostudiesMount"
lets just call it `biostudies-workdir`

2023-02-20 11:23 UTC, Juan-EBI commented on src/test/kotlin/listener/TestListener.kt
> +        runCatching { biostudiesEnv.start() }.getOrThrow()
this does nothing as it capture the exception and then throw it.

2023-02-20 11:23 UTC, Juan-EBI commented on src/test/resources/docker/docker-compose.yml
> +    command: docker login dockerhub.ebi.ac.uk -u $DOCKER_USER -p $DOCKER_PASSWORD
this is not needed it. Is it?

2023-02-23 11:22 UTC, msrada94 commented on .gitlab-ci.yml
> +    - gradle clean build -PbiostudiesDir=$BIOSTUDIES_DIR -PdockerUser=$CI_REGISTRY_USER -PdockerPassword=$CI_REGISTRY_PASSWORD --stacktrace
that's true those gradle properties are not needed

2023-02-23 11:33 UTC, msrada94 commented on src/test/resources/docker/docker-compose.yml
> +    command: docker login dockerhub.ebi.ac.uk -u $DOCKER_USER -p $DOCKER_PASSWORD
wont be needed after this changes

2023-02-23 12:06 UTC, msrada94 commented on src/test/kotlin/listener/TestListener.kt
> +        runCatching { biostudiesEnv.start() }.getOrThrow()
yes it does. i got rid of this

2023-02-26 21:14 UTC, Juan-EBI approved these changes
LGTM

2023-02-27 08:10 UTC, merged