Pivotal ID # 184009181: Implementation 3.1 test case in e2es
EBIBioStudies/biostudies-e2e pull request #4
Opened 2022-12-11 17:23 UTC by msrada94

https://www.pivotaltracker.com/story/show/184009181

-  First test case in the FileList feature

2022-12-11 18:52 UTC, Juan-EBI requested changes
Looking good please check comments

2022-12-11 18:52 UTC, Juan-EBI commented on src/test/kotlin/test/steps/BasicSteps.kt
> +    fun setStringVariableUsingMut(variableName: String, value: String) {
is pretty obvios it is string value it can be simple be call setVariableUsingMut (same bellow)

2022-12-11 18:52 UTC, Juan-EBI commented on src/test/resources/features/3-fileListSubmission.feature
> +    {"accno": "S-BSST130", "attributes": [{"name": "Title", "value": "Test Submission"},{"name": "ReleaseDate", "value": "2021-02-12"}], "section": {"accno": "SECT-001", "type": "Study", "attributes"
lets use a more json redable format

2022-12-11 18:52 UTC, Juan-EBI commented on src/test/resources/features/3-fileListSubmission.feature
> +    [{"path":"file4.txt","size":12,"attributes":[{"name":"GEN","value":"ABC"}],"type":"file"}]
it needs to be human redable json, which means we need to implement a json like assertion (to ignore spaces and json format at comparison time. ) To favor re use we probably need to store file content in variable and then assert using is jsonEquivalent or something like that step.

2022-12-11 18:52 UTC, Juan-EBI commented on src/test/resources/features/3-fileListSubmission.feature
> +    * the variable "storageMode" with value "NFS"
lets move this one to test background so we can change it easily (for both NFS/FIRE dual execution)

2022-12-11 18:52 UTC, Juan-EBI commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        bodyTable.mapValues { unwrapIfOne(it.value) }.forEach { map -> addToFormData(map) }
need re desng this function can be more simple, lets focus in solve the business case which is super simple

2022-12-11 20:24 UTC, msrada94 commented on src/test/kotlin/test/steps/HttpSteps.kt
> +        bodyTable.mapValues { unwrapIfOne(it.value) }.forEach { map -> addToFormData(map) }
You're right, I complicated myself. Already changed it, wrote it better

2022-12-11 20:51 UTC, msrada94 commented on src/test/resources/features/3-fileListSubmission.feature
> +    [{"path":"file4.txt","size":12,"attributes":[{"name":"GEN","value":"ABC"}],"type":"file"}]
Done! I used JSONAssert

2022-12-14 21:39 UTC, Juan-EBI approved these changes
LGTM

2022-12-14 22:17 UTC, merged