Pivotal ID # 184023382: Implementation 5.1 test case in e2es
EBIBioStudies/biostudies-e2e pull request #6
Opened 2022-12-13 11:16 UTC by msrada94

https://www.pivotaltracker.com/story/show/184023382

List of the changes:
* add scenario resubmit with files changed
* readability improvements

2022-12-14 21:40 UTC, Juan-EBI requested changes
please check comments

2022-12-14 21:40 UTC, Juan-EBI commented on src/test/kotlin/test/steps/IOSteps.kt
> +        val file = tempFile.toPath().resolve(fileName).apply { deleteIfExists() }
lets remove this create a file should fail if a file already exits

2022-12-14 21:40 UTC, Juan-EBI commented on src/test/resources/features/5-resubmit.feature
> +    And the file "$ftpUrl/S-BSST/500/S-BSST500/Files/a/Files/a/fileFileList.pdf" has content:
this path looks incorrect this should not be passing.

2022-12-16 20:54 UTC, msrada94 commented on src/test/kotlin/test/steps/IOSteps.kt
> +        val file = tempFile.toPath().resolve(fileName).apply { deleteIfExists() }
is not clear to me why should i remove this part. It is used in case we want to overwrite a file

2022-12-21 21:23 UTC, Juan-EBI requested changes
please check comments

2022-12-21 21:23 UTC, Juan-EBI commented on src/test/kotlin/test/steps/IOSteps.kt
> +        val file = tempFile.toPath().resolve(fileName).apply { deleteIfExists() }
a test failing because it is trying to create a file that already exists is the expected scenario,  that means this is is not seting the conditions for its execution or another test is not cleaning its data. We should not create steps ignores this errors but rather fix errors in the root cause.

2022-12-21 21:23 UTC, Juan-EBI commented on src/test/resources/features/5-resubmit.feature
> +  Scenario: 5.1 resubmit existing submission with changed files.
names need to match exactly the name of itests

2022-12-21 21:23 UTC, Juan-EBI commented on src/test/resources/features/5-resubmit.feature
> +    And the file "$ftpUrl/S-BSST/500/S-BSST500/Files/a/Files/a/fileFileList.pdf" has content:
this path is still incorrect

2022-12-21 22:28 UTC, msrada94 commented on src/test/kotlin/test/steps/IOSteps.kt
> +        val file = tempFile.toPath().resolve(fileName).apply { deleteIfExists() }
agree, thanks for this comment

2023-01-02 19:41 UTC, Juan-EBI commented
@msrada94 please resolve conflicts

2023-01-03 12:43 UTC, Juan-EBI approved these changes
LGTM

2023-01-03 12:45 UTC, Juan-EBI requested changes

2023-01-03 12:45 UTC, Juan-EBI commented on src/test/kotlin/test/steps/IOSteps.kt
> +        val file = tempFile.toPath().resolve(fileName).apply { deleteExisting() }
here we need to change file text not delete and create a new one, step and implementation does not match.

2023-01-03 14:26 UTC, Juan-EBI approved these changes
LGTM

2023-01-03 14:41 UTC, merged